### ISSUE TITLE
Implement proposed changes to Getting Started guide

### ISSUE THREAD

**Issue by kprosise** [NetworkGradeLinux/mion-docs#100]
The checklist can be removed. A walk-through example with screenshots and estimated time needed for each step needs to be added after then command examples.

**Comment by stunthamster** [comment]
I'm thinking we add this action to the repo: https://github.com/marketplace/actions/markdown-linting-action

If no one objects, I can go ahead and raise a PR with that.

**Comment by kprosise** [comment]
No objections here. Also  see mion-docs #90, which is more related to implementing a linter. Originally the idea for  #90 was to create a linter, however with a markdown linter already available, the only work that would need to be done is defining rules.

**Comment by kprosise** [comment]
For the time being, I am moving this issue back to to-do.  My reasoning is will be changes for 0.9.1 that may look a bit different than where things currently stand, so I'm going to wait for the dust to settle a bit first. If folks feel that I should just go ahead with where things are now, I can totally do that as well.

**Comment by kprosise** [comment]
Adding to this issue: getting started guide needs to be update for next release to include changes that are in mion/README.md dunfell-next branch

**Comment by kprosise** [comment]
> Adding to this issue: getting started guide needs to be update for next release to include changes that are in mion/README.md dunfell-next branch

Updated and merged already due to urgency.

**Comment by kprosise** [comment]
Putting this on hold, nearly complete, but other higher priority tasks must be addressed first.

**Comment by kprosise** [comment]
also adding update to mc_build.sh to include the vendor flag
