### ISSUE TITLE
Change doc site homepage to serve as entry point to project

### ISSUE THREAD

**Issue by kprosise** [NetworkGradeLinux/mion-docs#136]
<https://docs.mon.io> Home page (index.md) should explain in greater detail what it is, how it emerged out of a specific need, and what our vision is. 

In addition, the about page and home page overlap a bit, when they need to each have have unique and specific content.

**Comment by kprosise** [comment]
draft version added at https://github.com/NetworkGradeLinux/mion-docs/blob/dunfell/_drafts/index.md @benvantende and @johntoomey, if this can be reviewed for accuracy and overall content, that would be awesome. Changes can be made to it using the github editor and I'll approve and any PR's, and will then move it out of _drafts and do a formal commit.

**Comment by johntoomey** [comment]
done
