### ISSUE TITLE
Switch hardware features and support matrix

### ISSUE THREAD

**Issue by johntoomey** [NetworkGradeLinux/mion-docs#144]
Its probably necessary to explicitly enumerate all of the main switches we are supporting along with whatever information might me important (vendor,cpu,ram,asic,kernel ver,etc.) and maybe a feature matrix of stuff that is working/broken/unsupported. this would need to be updated for each release..

**Comment by johntoomey** [comment]
This should probably live in the new wiki as it is developer focused.

**Comment by johntoomey** [comment]
Initial list added here https://github.com/NetworkGradeLinux/mion-docs/wiki/Mion-supported-switches

Passing over to @kprosise to help fill in the remaining blanks..

Could possibly add columns for kernel version, sde version, known issues but i think this would be overkill at the moment..

**Comment by kprosise** [comment]
All seems fine, and qemu info has been updated and added to the wiki, and a last moment change to mion capitalization.  Copying over to mion-docs will be done during the release process. Of course it's a living document, and we can update it as needed. 

Closing issue as document passed review.
