### ISSUE TITLE
documentation community page

### ISSUE THREAD

**Issue by johntoomey** [NetworkGradeLinux/mion-docs#145]
something other than contributing that shows people the slack (and other comms channels as they are added), how to log bugs and where they are tracked and a list of public meetings

**Comment by kprosise** [comment]
Even though I'm thinking of a little bit different and more basic, I frequently like to check out how the Yocto Project does stuff: https://www.yoctoproject.org/community/

At the very least it's a good summary of what topics we may want to have.

**Comment by kprosise** [comment]
draft has been placed in https://github.com/NetworkGradeLinux/mion-docs/blob/dunfell/_drafts/Community.md, after review by @benvantende we will move it from _drafts to docs/community.

**Comment by kprosise** [comment]
Added community page,  though the page will need to (1) be updated with new community meeting information and (2) eventually moved to the NGL website.
