### ISSUE TITLE
Test plan for mion

### ISSUE THREAD

**Issue by toganlabs** [NetworkGradeLinux/mion-docs#168]
Unit tests, integration tests, platform tests?

**Comment by kprosise** [comment]
Outline and draft largely finished, however there are a number of topics that need to be filled in, both partially and entirely. Oh and it needs to pass the QA process for documentation. 



If @CommitThis, @toganlabs and @johntoomey could take a look at this and either add info or send me info to add, that would be much appreciated.  and feedback always welcomed.

**Comment by johntoomey** [comment]
ok - i have split the testing documentation into two different documents - 
- https://github.com/NetworkGradeLinux/mion-docs/wiki/Automated-testing -and-
- https://github.com/NetworkGradeLinux/mion-docs/wiki/Release-Test-plan

the intention here is that the CI/automated testing should be dealt with separately from the pre-release test process - these documents are a bit of a mess now but myself and @kprosise are going to tag-team them for a while until they are a bit more polished. the automated testing might be fairly static but the release test plan will be a living document that should be updated before/after each release as we go..

**Comment by johntoomey** [comment]
Ok - calling this one done for now after several people have had a look at it. 

The list of tests are incomplete and we will have to review it before every future release to try to add and update as we go along but lets see how this works for this release.. 

Test output can be found here https://docs.google.com/spreadsheets/d/1ajP_V8e8Br2KMgCqQGceh9JOeGntOEEXv2eQW0JS7lc/edit#gid=247801303
