### ISSUE TITLE
mion: Glossary

### ISSUE THREAD

**Issue by CommitThis** [NetworkGradeLinux/mion-docs#17]
There are a lot of terms used in embedded Linux, crossing Oryx, Yocto, OpenEmbedded.

A glossary is therefore necessary to explain these terms and have them as being identifiable as being associated with a particular component. e.g. `bitbake` is a build tool co-maintained by Yocto and OpenEmbedded; _Application Profiles_ are a concept in Oryx/Mion etc.

https://github.com/APS-Networks/high-level-documentation/blob/glossary/glossary.md

**Comment by kprosise** [comment]
glossary has been updated. While the glossary is a "living document", most current and relevant terms have been added.
