### ISSUE TITLE
Documentation needs a QA process

### ISSUE THREAD

**Issue by toganlabs** [NetworkGradeLinux/mion-docs#171]
Prior to release, we need to QA the documentation in order to ensure that the documentation is correct and up to date with the release.

**Comment by kprosise** [comment]
I've decided to move this into "In progress", as it's being covered in a subsection of the test plan wiki document.

**Comment by kprosise** [comment]
Documentation QA process has been added to the wiki, with sections for both general and release candidate testing. See

https://github.com/NetworkGradeLinux/mion-docs/wiki/Test-plan

We can close this issue after the doc sections are reviewed and approved.
