### ISSUE TITLE
Do Documentation Release Process

### ISSUE THREAD

**Issue by kprosise** [NetworkGradeLinux/mion-docs#179]
The following documentation tasks need to be done for the 2021.03 release. Tasks are separated by dependence on changes made by engineering...Engineers/Maintainers should update README's and any technical documentation that may have had last minute changes.

Dependent on engineering (can't be done until all changes final):

- [x] Add documentation on how to build stratum and link to any relevant stratum
      docs
- [x] Add documentation on sde
- [x] sync mion-docs with changed repo based documentation (i.e readme files)
- [x] Release notes of all changes and known issues added to mion-docs
- [x] run **all remaining** docs through QA
- [x] Community lead is updated of all new features/improvements

Independent of engineering:

- [x] sync dunfell and gh-pages content *carefully*
- [x] Update labels(latest, dev) associated with releases
- [x] Add table of supported platforms to mion-docs
- [x] Update home page: version notice, dev wiki link, copyright/trademark blurb
- [x] Run completed documentation through QA

**Comment by N-Mc-Nally** [comment]
Thanks @kprosise, this is awesome :-)

**Comment by kprosise** [comment]
Woot! And we are done!
