### ISSUE TITLE
mion: Front Page Content

### ISSUE THREAD

**Issue by CommitThis** [NetworkGradeLinux/mion-docs#20]
The front page really needs to be brief and covers the most important aspects of the OS.

We have a pretty good lede at this point, but everything after that is up for grabs.

Some things that could be considered is anything that ties up with updates, supportability security that kind of thing. Also might be worthwhile commenting or at least briefly listing the major sponsors.

Also perhaps provide some links to launch to other sections of the site.

**Comment by kprosise** [comment]
Duplicate, closing.
