### ISSUE TITLE
Document SDE upgrade info

### ISSUE THREAD

**Issue by kprosise** [NetworkGradeLinux/mion-docs#202]
SDE changes will need to be documented *if* they happen for the 2021.06 release. If we are short on time, this can be included in [Adds and Ends](https://docs.mion.io/2021.06-dev/adds-and-ends/)

**Comment by johntoomey** [comment]
Need to fully document how to use the SDE on the wiki and provide a link in the stratum doc
- https://github.com/NetworkGradeLinux/mion-docs/wiki/Barefoot-SDE
- https://github.com/NetworkGradeLinux/mion-docs/wiki/Stratum

**Comment by toganlabs** [comment]
I've documented in the Barefoot-SDE wiki how to upgrade and how we're implemented a reference build of it and leave it up as an exercise for the reader to implement their own SDE build.
