### ISSUE TITLE
Document Stratum 

### ISSUE THREAD

**Issue by kprosise** [NetworkGradeLinux/mion-docs#203]
Stratum info will need to be added to the main docs and any relevant repo level docs. if time is short, this can at least be included in [Adds and Ends](https://docs.mion.io/2021.06-dev/adds-and-ends/)

**Comment by johntoomey** [comment]
on hold pending the outcome of https://github.com/NetworkGradeLinux/meta-mion/issues/73

**Comment by johntoomey** [comment]
Added a basic Stratum page to the wiki https://github.com/NetworkGradeLinux/mion-docs/wiki/Stratum-%5BWIP%5D

@CommitThis is going to take a look and help fill out some of the missing info

**Comment by johntoomey** [comment]
Updated wiki page on stratum installation linked above. documentation needs to be written for the Barefoot SDE but im calling this one done for now.
