### ISSUE TITLE
Document TN48m and DENT

### ISSUE THREAD

**Issue by kprosise** [NetworkGradeLinux/mion-docs#204]
When merged, this will need to be documented. If time is short, this can be a couple lines covering [Adds and Ends](https://docs.mion.io/2021.06-dev/adds-and-ends/)

**Comment by johntoomey** [comment]
@toganlabs - these needs to be updated 
- https://github.com/NetworkGradeLinux/mion-docs/blob/dunfell/docs/supported-switches.md 
- https://github.com/NetworkGradeLinux/mion-docs/wiki/mion-supported-switches

**Comment by toganlabs** [comment]
Added to the wiki and opened pr for docs.

https://github.com/NetworkGradeLinux/mion-docs/pull/232
