### ISSUE TITLE
Document Current Container Story

### ISSUE THREAD

**Issue by kprosise** [NetworkGradeLinux/mion-docs#205]
mion is changing how containers are utilized in a number of ways, and this should be well documented....how it did work, how it currently works, and what it may look like in the feature. 

Add note about meta-mion-unsupported,  and k3s in m-m-backports

**Comment by johntoomey** [comment]
First draft pushed for review here - https://github.com/NetworkGradeLinux/mion-docs/pull/209

@kprosise can you take a look at this and figure out how to move/rename it to something more appropriate?

**Comment by kprosise** [comment]
Moving back to in progress. The most necessary edits will be made first. If time allows, the topic will be further detailed.

**Comment by kprosise** [comment]
closed with #215
