### ISSUE TITLE
Document onie only build option

### ISSUE THREAD

**Issue by kprosise** [NetworkGradeLinux/mion-docs#206]
ONIE only build script doesn't use multiconfig. This needs to be documented on the main docs and anywhere else where it may apply.

**Comment by johntoomey** [comment]
after discussing with @kprosise - this needs to be updated in the following locations:
- GSG - text and image
- mion top level repo - README
- adds and ends - @kprosise is going to do this one

**Comment by johntoomey** [comment]
here is the GSG update https://github.com/NetworkGradeLinux/mion-docs/pull/212 first pass

**Comment by johntoomey** [comment]
Updated GSG https://github.com/NetworkGradeLinux/mion/pull/131 first pass, will probably need more work

**Comment by kprosise** [comment]
PR #217 adds screenshots of `cronie.sh` invocation, replacing `mc_build.sh`. Editorial changes applied to the work @johntoomey did to the getting started guide.

**Comment by kprosise** [comment]
Finished with PR #218. May further edit the adds and ends to better work in a pun, if time permits.
