### ISSUE TITLE
Document Aliases Shell Script Addition

### ISSUE THREAD

**Issue by kprosise** [NetworkGradeLinux/mion-docs#207]
`meta-mion/recipes-core/base-files/files/00-aliases.sh` was added during the resturctureing of meta-mion. Document it's existence and purpose.

**Comment by johntoomey** [comment]
after discussion with @kprosise - we are going to add a wiki page relating to customisation which can be moved to the docs later if necessary - https://github.com/NetworkGradeLinux/mion-docs/wiki/Customising-Mion

**Comment by johntoomey** [comment]
@kprosise the above wiki page has a few lines explaining this - could you take a look when you get a chance and close this issue if you are happy with it?

**Comment by kprosise** [comment]
This looks fine for the wiki, closing issue
