### ISSUE TITLE
Document meta-mion restructuring

### ISSUE THREAD

**Issue by kprosise** [NetworkGradeLinux/mion-docs#208]
meta-mion  was restructured. This needs to be documented, likely in the "Adds and Ends" and the more traditional change log.

**Comment by johntoomey** [comment]
Pushed for review here https://github.com/NetworkGradeLinux/mion-docs/pull/210 and assigned to @kprosise

**Comment by kprosise** [comment]
merged into the Dunfell branch, but will need changes before publishing. Moving this back into todo rather than review as editing is required.
