### ISSUE TITLE
mion: How To Guides

### ISSUE THREAD

**Issue by CommitThis** [NetworkGradeLinux/mion-docs#21]
Self explanatory. Possibly things like:

* Reprovisioning with mender (os image/container)
* Stopping starting containers (or general container management)

Also, it might be worth having two sets of docs, one for explanatory notes for the various components, but also for guides like this that walk through various aspects of the system.

**Comment by kprosise** [comment]
The topics listed are covered by other issues, and for the sake of keeping the open issues less cluttered and more specific, I'm closing this issue. It can be re-opened if needed.
