### ISSUE TITLE
mion: Explain Yocto Metaphors

### ISSUE THREAD

**Issue by CommitThis** [NetworkGradeLinux/mion-docs#29]

**Comment by johntoomey** [comment]
This is probably out of scope for the mion docs - possibly link to existing yocto docs if they have something similar rather than creating something new. @kprosise to confirm that this is ok not to do.

**Comment by kprosise** [comment]
yes, it's a fun little documentation thing, and though nothing exists that explains this to my knowledge, it's not really needed, so closing it now, could always do at a later point if time and resources permit. Closing issue.
