### ISSUE TITLE
Documentation Structure

### ISSUE THREAD

**Issue by CommitThis** [NetworkGradeLinux/mion-docs#33]

**Comment by kprosise** [comment]
@CommitThis, reviewing this issue, I wanted to check in about what work, if any, needs to be done on this in order to close it. There's a couple things that come to mind on how "documentation structure" could be interpreted. I'm sure this was discussed back in September, but it's been awhile.

**Comment by CommitThis** [comment]
@kprosise I'm pretty sure at this point, it's all been covered; back when this was first discussed, there were quite a few more subjects and pages. I think this can be closed.

**Comment by kprosise** [comment]
@CommitThis, that's my thought as well, I'll go ahead and close it.
