### ISSUE TITLE
mion: Platform and Application Support

### ISSUE THREAD

**Issue by CommitThis** [NetworkGradeLinux/mion-docs#4]
Discuss platform support, e.g:
* ONLP
* Stratum
* SAI

Do we take an opinionated approach? What is it by default, none or ONLP?

How are these supported? Best efforts? Guaranteed support? If best-effort, how do we justify that against the lede of being secure and stable?
Probably not, but Is discussing a cost model appropriate here?

**Comment by johntoomey** [comment]
this is no longer valid - @CommitThis to confirm?

**Comment by CommitThis** [comment]
@johntoomey I think we can bin this one. Application support seems to be progressing pretty naturally.
