### ISSUE TITLE
DOCS: Need to be able to show versioned docs on website. (ie 2020.12/docs 2021.03/docs) as things will change from release to release

### ISSUE THREAD

**Issue by johntoomey** [NetworkGradeLinux/mion-docs#87]

**Comment by kprosise** [comment]
Three options to consider:

* move to [Read The Docs](https://readthedocs.org/)
* Use a workaround to [implement versioning using collections with Jekyll](https://github.com/justwriteclick/versions-jekyll)
* Switch from jekyll to MkDocs, which has plugins for versioning, needs to be tested

This should be discussed during the next documentation meeting. For the time being, I will set up a local instance of MkDocs. MkDocs is pretty straight forward and not dissimilar to Jekyll, and as it is supported by Read The Docs, which would make importing if we go that route easier. I'll present my work and findings during the docs meeting on 2021-01-14.

**Comment by kprosise** [comment]
I've decided that, while I will continue to look at and raise discussions about alternatives, I will implement versioning using collections in Jekyll for the time being. With new documentation to be added soon, I want to get versioning done before the end of this week.

**Comment by kprosise** [comment]
Docs are currently being switched from jekyll to mkdocs

**Comment by kprosise** [comment]
moved to Blocked/Hold until questions on versioning strategy and a few other implementation details are ironed out.
