### ISSUE TITLE
For doc/website development, we need to have a testing site so that we don't have failures occurring on public accessible sites.

### ISSUE THREAD

**Issue by johntoomey** [NetworkGradeLinux/mion-docs#88]

**Comment by kprosise** [comment]
There's issues surrounding hosting and the use of the same theme. After looking into it a bit and trying out a couple approaches, there's currently no way to do this that doesn't make maintaining and contributing to mion-docs easier with current resources. 

For allowing quick testing and collaboration, mion-docs has the `_drafts` folder; the use of this folder and how it fits into the workflow will be documented in `mion-docs/CONTRIBUTING.md`. Documentation on how to set up a local Jekyll site will also be updated to make it more accessible.  In the end this is  likely less messy than having a separate site.

I've decided to close this issue, if anyone feels that it should be re-opened, or has any questions, feel free to let me know.
