### ISSUE TITLE
mion: Define Specific Contributions

### ISSUE THREAD

**Issue by CommitThis** [NetworkGradeLinux/mion-docs#9]
I think it's fair to say that BISDN has been fairly important in delivering the P.O.C. We need to make sure that they are credited appropriately. This ties in with #8

**Comment by kprosise** [comment]
Is this something that is still relevant?

**Comment by CommitThis** [comment]
Well it might be worth pointing out to that BISDN laid quite a lot of
groundwork.

Other sponsors or contributor as well, maybe even Commit This ;)



*Gawen Davey*
Director
Commit This Limited
